# Generated by Django 4.1 on 2023-01-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(
                blank="True", default="", upload_to="post/cover/%Y-%m-%d/"
            ),
        ),
    ]
