# Generated by Django 4.1 on 2023-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sub_title",
            field=models.CharField(
                default="", max_length=250, verbose_name="Subtitulo"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(
                blank="True",
                default="",
                upload_to="post/cover/%Y-%m-%d/",
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(verbose_name="Texto"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=70, verbose_name="Titulo"),
        ),
    ]
