# Generated by Django 4.1 on 2023-01-26 18:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_sub_title_alter_post_cover_alter_post_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="t",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
