# Generated by Django 4.1 on 2023-01-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_t"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="t",),
    ]
