# Generated by Django 4.1 on 2023-01-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_post_t"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.FileField(
                blank="True",
                default="",
                upload_to="post/imagens/%Y-%m-%d/",
                verbose_name="Imagens",
            ),
        ),
    ]
