# Generated by Django 4.1 on 2023-01-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="images",),
    ]
